### ISSUE TITLE
GMTA source

### ISSUE THREAD

**Issue by Wzlzh123** [icey-zhang/E2E-MFD#12]
寻找论文中GMTA显示梯度调整的源代码

**Comment by SwordShiSan** [comment]
同问，希望可以给出在开源代码中具体的GMTA实现方式，谢谢！

**Comment by ironmanfcf** [comment]
我也发现了这一问题，下图是作者的源代码，我按照redme的指导可以跑通网络，但是网络在训练时并没有经过这一流程。至于这一份部分的代码，除了有注释，我并没有发现相较于源代码的改动。希望有人可以解答疑惑，即如何在E2EMFD的训练流程中实现GMTA这一过程。
![image](https://github.com/user-attachments/assets/d377b791-f4da-453c-b0cf-675f50ad2f6f)

**Comment by shawwalt** [comment]
您好，方便分享下数据集是怎么加载的吗？我把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，而且我看DroneVehicle类里面标记文件不是.xml是.txt，现在很困惑

**Comment by Wzlzh123** [comment]
85 376 110 375 118 439 94 445 car 0
118 372 151 372 151 443 119 442 car 0
158 447 186 446 191 378 158 376 car 0
194 443 221 447 227 389 198 388 car 0
148 281 177 280 178 224 151 222 car 0
187 282 213 282 211 221 187 222 car 0
248 217 280 216 277 283 248 279 car 0
288 274 317 283 328 217 299 211 car 0
332 324 332 295 402 298 403 331 car 0 这是我的数据集形式

**Comment by Wzlzh123** [comment]
[labels.zip](https://github.com/user-attachments/files/18058632/labels.zip)
我的train的labels

**Comment by shawwalt** [comment]
可以请问下opencv版本4.10.0.84报这个问题是如何解决的吗？
<img width="514" alt="Snipaste_2024-12-09_17-26-12" src="https://github.com/user-attachments/assets/81d1a31d-4a55-4153-a717-0d74ac50328a">

**Comment by shawwalt** [comment]
图片是.jpg格式

**Comment by suibiandefansi** [comment]
> 您好，方便分享下数据集是怎么加载的吗？我把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，而且我看DroneVehicle类里面标记文件不是.xml是.txt，现在很困惑

您好，可否请问一下这个问题解决了吗？我也是把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，标记文件用.txt或者.xml都加载不出来任何图片或者标签。看build_dataset函数好像没有对cfg的'img_prefix'路径进行读取

**Comment by shawwalt** [comment]
你看配置文件dronevehicle_m里面不是有个data.test吗，我改了那个就能正常跑了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月11日(周三) 中午12:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [icey-zhang/E2E-MFD] 源代码查询问题 (Issue #12)




  
您好，方便分享下数据集是怎么加载的吗？我把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，而且我看DroneVehicle类里面标记文件不是.xml是.txt，现在很困惑
  
您好，可否请问一下这个问题解决了吗？我也是把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，标记文件用.txt或者.xml都加载不出来任何图片或者标签。看build_dataset函数好像没有对cfg的'img_prefix'路径进行读取

**Comment by shawwalt** [comment]
然后img_prefiz作者在另外一个issue说了要设成可见光图像路径，label设成是ir的label



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月11日(周三) 中午12:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [icey-zhang/E2E-MFD] 源代码查询问题 (Issue #12)




  
您好，方便分享下数据集是怎么加载的吗？我把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，而且我看DroneVehicle类里面标记文件不是.xml是.txt，现在很困惑
  
您好，可否请问一下这个问题解决了吗？我也是把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，标记文件用.txt或者.xml都加载不出来任何图片或者标签。看build_dataset函数好像没有对cfg的'img_prefix'路径进行读取

**Comment by suibiandefansi** [comment]
> 然后img_prefiz作者在另外一个issue说了要设成可见光图像路径，label设成是ir的label
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月11日(周三) 中午12:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [icey-zhang/E2E-MFD] 源代码查询问题 (Issue #12) 您好，方便分享下数据集是怎么加载的吗？我把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，而且我看DroneVehicle类里面标记文件不是.xml是.txt，现在很困惑 您好，可否请问一下这个问题解决了吗？我也是把data_root换成自己的DroneVehicle根路径但是数据集加载不进来，标记文件用.txt或者.xml都加载不出来任何图片或者标签。看build_dataset函数好像没有对cfg的'img_prefix'路径进行读取 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，加载出来了，非常感谢！

**Comment by shawwalt** [comment]
> 我也发现了这一问题，下图是作者的源代码，我按照redme的指导可以跑通网络，但是网络在训练时并没有经过这一流程。至于这一份部分的代码，除了有注释，我并没有发现相较于源代码的改动。希望有人可以解答疑惑，即如何在E2EMFD的训练流程中实现GMTA这一过程。 ![image](https://private-user-images.githubusercontent.com/108777410/392217374-d377b791-f4da-453c-b0cf-675f50ad2f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjIyNzksIm5iZiI6MTczNDI2MTk3OSwicGF0aCI6Ii8xMDg3Nzc0MTAvMzkyMjE3Mzc0LWQzNzdiNzkxLWY0ZGEtNDUzYy1iMGNmLTY3NWY1MGFkMmY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMTI2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmMxNDU4OGMyYzU4NGEwZjk0MjA5ODE2YTk1NDk1MmRlN2E1NTA2M2U3OWFhZDZmZWQwZmZiMTMzNmVkZThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ku_4VlRsY9fsRFwcyQqeqAADkSbFQPYqfoVnDm5ZgyE)

您好，您解决了这个问题吗？为什么训练时没有经过这一部分，是否是因为程序实际执行的是anaconda/envs里的adm，而并没有执行本目录下的adm呢？如果是，您是如何在anaconda/envs目录下进行调试的？

**Comment by 123wangyule** [comment]
解决了这一问题，这一流程的代码不是在环境中，而是在mmrotate/adm中，之前我跑的时候代码使用的optimizerhook不是作者改动过的，可能采用的错误的，导致没有经过这个流程。

**Comment by shawwalt** [comment]
但我之前调试的时候把他修改过的optimizer.py放到env里，不然会报错，他在那个里面import了adm，然后我就把adm和那个文件放到同级目录下，然后就能正常跑了，现在程序调用的应该是sitepackage里面的那个adm，但我没法调试那里，想问下你是咋搞的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月15日(周日) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [icey-zhang/E2E-MFD] 源代码查询问题 (Issue #12)




 
解决了这一问题，这一流程的代码不是在环境中，而是在mmrotate/adm中，之前我跑的时候代码使用的optimizerhook不是作者改动过的，可能采用的错误的，导致没有经过这个流程。

**Comment by elaaaar** [comment]
> 你看配置文件dronevehicle_m里面不是有个data.test吗，我改了那个就能正常跑了
> […](#)

您好，请问您提到的“配置文件dronevehicle_m里面不是有个data.test吗"中的data.test具体指的是什么呀？

**Comment by HaOn1230** [comment]
> [labels.zip](https://github.com/user-attachments/files/18058632/labels.zip) 我的train的labels
你的这个labels后面全是空的
