### ISSUE TITLE
图像数据加载不出来

### ISSUE THREAD

**Issue by suibiandefansi** [icey-zhang/E2E-MFD#19]
您好，可否请问一下按照readme指示后运行代码读取到的数据集为0是什么原因吗？val_dataloader没有任何数据，数据集准备是按照指示进行的。看build_dataset好像没有对'img_prefix'路径进行读取
![微信图片_20241211122406](https://github.com/user-attachments/assets/3b578319-8600-4b84-81c1-de97edc79e20)

**Comment by UnchangedOriInten** [comment]
The  format of labels is txt,not xml.

**Comment by suibiandefansi** [comment]
> 标签的格式是txt，而不是xml。
好的，谢谢！
