### ISSUE TITLE
请问M3FD数据集是如何划分的训练集和验证集？

### ISSUE THREAD

**Issue by leileilei2000** [icey-zhang/E2E-MFD#2]

**Comment by kaka-Cao** [comment]
数据集是随机划分的，想保持一致的话，请直接在下面网盘下载：
链接：https://pan.baidu.com/s/1kervmYjbvmYL2Fjv8jQ91Q 
提取码：3xsb

**Comment by jimuIee** [comment]
> 数据集是随机划分的，想保持一致的话，请直接在下面网盘下载： 链接：https://pan.baidu.com/s/1kervmYjbvmYL2Fjv8jQ91Q 提取码：3xsb

请问作者尝试过使用mm的框架进行m3fd数据集的检测训练吗，我将m3fd的数据按照mm系列的格式转化了一下，但是运行过程在图像归一化中报错了（其中路径划分与Dronevehicle一致）
具体报错呈现说尺寸不匹配
/mydata/anaconda3/envs/E2E-MFD/lib/python3.9/site-packages/mmcv/image/photometric.py", line 53, in imnormalize_
    cv2.subtract(img, mean, img)  # inplace
cv2.error: OpenCV(4.10.0) /io/opencv/modules/core/src/arithm.cpp:658: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels),

config文件如下：
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImagePairFromFile', spectrals=('rgb', 'ir')),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(768, 1024)),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle_m'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImagePairFromFile', spectrals=('rgb', 'ir')),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(768, 1024),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle_m'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=8,
    train=dict(
        type='M3FDDataset',
        ann_file='/mydata/E2E-MFD-main/M3FD/train/rgb/txtlabels/',
        img_prefix='/mydata/E2E-MFD-main/M3FD/train/rgb/images/',
        pipeline=[
            dict(type='LoadImagePairFromFile', spectrals=('rgb', 'ir')),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize', img_scale=(768, 1024)),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle_m'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        version='le90'),
    val=dict(
        type='M3FDDataset',
        ann_file='/mydata/E2E-MFD-main/M3FD/test/rgb/txtlabels/',
        img_prefix='/mydata/E2E-MFD-main/M3FD/test/rgb/images/',
        pipeline=[
            dict(type='LoadImagePairFromFile', spectrals=('rgb', 'ir')),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(768, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle_m'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'),
    test=dict(
        type='M3FDDataset',
        ann_file='/mydata/E2E-MFD-main/M3FD/test/rgb/txtlabels/',
        img_prefix='/mydata/E2E-MFD-main/M3FD/test/rgb/images/',
        pipeline=[
            dict(type='LoadImagePairFromFile', spectrals=('rgb', 'ir')),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(768, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle_m'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'))
