### ISSUE TITLE
Train DroneVehicle

### ISSUE THREAD

**Issue by StarBlue98** [icey-zhang/E2E-MFD#3]
Hello, thanks for your great work!
When training DroneVehicle dataset, I wonder whether the val set is used or the val set is add to form trainval set to train the model? 
Do I need to transform the label format (xml) into dota format, like the way  in mmrotate  (python tools/data/dota/split/img_split.py --base-json tools/data/dota/split/split_configs/ss_trainval.json)? 
How to  do multi-scale training and testing in DroneVehicle, could you provide a config you used ?
 Thanks so much

**Comment by kaka-Cao** [comment]
When training the DroneVehicle dataset, we only use the train partition for training and the test partition for testing. We do not use the val partition.
The images do not need to be preprocessed, and the labels are in the yolo txt format, for example:
254 259 256 321 279 318 275 258 car 0
We did not use multi-scale training. The configuration file of the dataset can be viewed in https://github.com/icey-zhang/E2E-MFD/blob/main/tools/cfg/dronevehicle_m.py
